name = "backend"
compatibility_date = "2024-09-11"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjE5MjliY2UtZmNmZS00N2YxLWE2ZjUtZjdmMDRjYWM4MmI4IiwidGVuYW50X2lkIjoiYWNkZWU3ZGYwZmY1NzcyZjEyYmM2YzA4NWIzYzNjNWQ2MjNmMGM5NzM4N2ZhNDY4MTYwMWY3ZTkyZDcwNWI5OSIsImludGVybmFsX3NlY3JldCI6ImI3NWFmZDEzLWI1ZjItNGVmMy05YWFkLTdhODRmNDBhNjQyNSJ9.3ISkvZh8eNx8DXOedUR3ANfGAYgJxo3IYAPNc1ZNcAA"
JWT_SECRET = "SECRET"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"